spring.application.name=gestor-leitura-api
spring.jackson.serialization.indent-output=true
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_leitura_db?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=ml28381923

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

google.books.api.url=https://www.googleapis.com/books/v1/volumes
google.books.api.key=AIzaSyAs-tgh7BvAAlz1U_GMOddtxYqN0MA3A7w